### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by wkirby** [facebookresearch/watermark-anything#1]
I believe this is the correct link: https://arxiv.org/abs/2411.07231

**Comment by millette** [comment]
Fixed.

**Comment by millette** [comment]
Now fixed https://github.com/facebookresearch/watermark-anything/commit/d7bc5dd177f3ae0dad5cc330254970c5dc2a4427

**Comment by pierrefdz** [comment]
Thanks a lot for rising this issue, it's fixed now
