### ISSUE TITLE
Release model on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [facebookresearch/watermark-anything#3]
Hello @pierrefdz 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through Hugging Face's daily papers: https://huggingface.co/papers/2411.07231. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the checkpoint you've pre-trained on https://huggingface.co/models? Hosting on Hugging Face will give you more visibility. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

Kind regards,

Niels

**Comment by pierrefdz** [comment]
Thanks for reaching out, I'll try to do this this weekend

**Comment by NielsRogge** [comment]
Great, let us know if you need any help 🤗

**Comment by xiaoyao9184** [comment]
need this feature, i have uploaded the model by [Action](https://github.com/xiaoyao9184/docker-wam/blob/main/.github/workflows/hf-model-commit-branch.yml) to my own namespace, which is obviously not a good idea.

**Comment by pierrefdz** [comment]
Updts: 
we should have a new model with better license before EOY, we'll release the model on HF at the same time

**Comment by pierrefdz** [comment]
-> https://huggingface.co/facebook/watermark-anything

**Comment by NielsRogge** [comment]
Thank you!!
