### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by ryabchenkoa** [facebookresearch/watermark-anything#4]
Hello!

First, thank you for the paper and the code, from the first looks of it, it seems to be a great leap in watermarking technology!
Since it seems that the technology can be quite useful for commercial use, do you have any plans to change the license to a commercial one like Apache 2.0 that you have for many other models? Or at least is it possible to buy a separate license for commercial use?

Thank you!

**Comment by pierrefdz** [comment]
Hi, at the moment the model is NC because we trained on images from COCO which are not permissive for redistribution.
I'll reach out to our legal teams to see what we can do with that regard.

**Comment by ryabchenkoa** [comment]
Thank you!

I was convinced that COCO is CC 4.0 and was not prohibitive for redistribution, since so many publish their models with permissive license and pre-train on COCO.

Please, let us know!

**Comment by pierrefdz** [comment]
FYI not all images in COCO have the same license. Some are CC BY, some are CC BY NC, etc.
Distribution of the images are the following:
![image](https://github.com/user-attachments/assets/3d542538-9887-40ec-bac1-6ee714425d6c)

**Comment by ryabchenkoa** [comment]
Ah, I see. CC4 is for annotations, you are absolutely right. 

In this case, would it be possible to have a separate licenses for the code and the weights? I.e. if the model could be trained from scratch on a custom dataset, then it wouldn't violate COCO's privacy.

**Comment by pierrefdz** [comment]
In my experience legals prefers to have a unique license. I'll come back to you with solutions soon

**Comment by ryabchenkoa** [comment]
Any update?

Thanks in advance!

**Comment by pierrefdz** [comment]
i don't want oversell, but there may be an update before the end of the year

**Comment by sandertom** [comment]
Hey @ryabchenkoa ! we just added a new model under the MIT license. Enjoy!
